---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: Production environment
  destinations:
    - namespace: '*'
      server: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - '*'
...
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prod-helm-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/queercoded-dev/argocd-queercoded-server.git
        revision: ""
        files:
          - path: apps/**/envs/values-prod.yaml
        requeueAfterSeconds: 20
        template:
          metadata: {}
          spec:
            destination: {}
            project: ""
            source:
              repoURL: ""
  template:
    metadata:
      labels:
        app.kubernetes.io/name: '{{ path[1] }}'
      name: prod-{{ path[1] }}
      namespace: argocd
    spec:
      project: prod
      destination:
        namespace: 'queercoded'
        server: 'https://kubernetes.default.svc'
      source:
        repoURL: https://github.com/queercoded-dev/argocd-queercoded-server.git
        targetRevision: 'main'
        path: '{{ path }}/../chart'
        helm:
          valueFiles:
            - '../envs/values-prod.yaml'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
...
